server:
  port: 9000

spring:
  application:
    name: gateway-demo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
          filters:
            - StripPrefix=1
      routes:
      - id:  path_route12
        uri: lb://wolf-pay1
        predicates:
        - Path=/wolf-pay/trade/record
        order: -1

logging.level.org.springframework.cloud.gateway: debug
logging.level.org.springframework.http.server.reactive: debug
logging.level.org.springframework.web.reactive: debug
logging.level.org.springframework.boot.autoconfigure.web: debug
logging.level.reactor.netty: debug
